[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Tetrahedralizer"
description="Generates a tetrahedral mesh from an external triangle mesh."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Example"

# Keywords for the extension
keywords = ["kit", "example"]

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import mnresearch.tetgen".
[[python.module]]
name = "mnresearch.tetgen"

[python.pipapi]
requirements = ['numpy', 'pxr', 'pyvista', 'tetgenExt==0.6.dev0', 'warp']
use_online_index = true
